<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: https://leo-editor.github.io/leo-editor/leo_toc.html -->
<leo_file xmlns:leo="https://leo-editor.github.io/leo-editor/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="gnx.1"><vh>Root</vh>
<v t="gnx.2"><vh>Child A</vh></v>
<v t="gnx.3"><vh>Child B</vh>
<v t="gnx.2"></v>
</v>
<v t="gnx.4"><vh>@bool minibuffer-find-mode = True</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="gnx.1">print("root body")</t>
<t tx="gnx.2">def foo():
    return 1
</t>
</tnodes>
</leo_file>
