<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
  <xsl:strip-space elements="*"/>

  <!-- Global variables -->
  <xsl:variable name="globalVar" select="/root/config/value"/>
  <xsl:variable name="literalVar">literal value</xsl:variable>

  <!-- Template with match -->
  <xsl:template match="/">
    <xsl:apply-templates select="root/items"/>
  </xsl:template>

  <!-- Template with match and mode -->
  <xsl:template match="item" mode="summary">
    <summary>
      <xsl:value-of select="@name"/>
    </summary>
  </xsl:template>

  <!-- Named template -->
  <xsl:template name="formatDate">
    <xsl:param name="date"/>
    <xsl:param name="format" select="'YYYY-MM-DD'"/>
    <formatted>
      <xsl:value-of select="$date"/>
    </formatted>
  </xsl:template>

  <!-- Template with various constructs -->
  <xsl:template match="items">
    <output>
      <!-- xsl:if -->
      <xsl:if test="count(item) > 0">
        <hasItems>true</hasItems>
      </xsl:if>

      <!-- xsl:choose/when/otherwise -->
      <xsl:choose>
        <xsl:when test="@type = 'A'">
          <type>Type A</type>
        </xsl:when>
        <xsl:when test="@type = 'B'">
          <type>Type B</type>
        </xsl:when>
        <xsl:otherwise>
          <type>Unknown</type>
        </xsl:otherwise>
      </xsl:choose>

      <!-- xsl:for-each -->
      <xsl:for-each select="item">
        <entry>
          <xsl:attribute name="id">
            <xsl:value-of select="@id"/>
          </xsl:attribute>
          <name><xsl:value-of select="name"/></name>
          <xsl:copy-of select="details/*"/>
        </entry>
      </xsl:for-each>

      <!-- xsl:call-template with params -->
      <xsl:call-template name="formatDate">
        <xsl:with-param name="date" select="@created"/>
        <xsl:with-param name="format">DD/MM/YYYY</xsl:with-param>
      </xsl:call-template>

      <!-- xsl:element and xsl:attribute -->
      <xsl:element name="dynamic">
        <xsl:attribute name="source">generated</xsl:attribute>
        <xsl:text>Some text content</xsl:text>
      </xsl:element>

      <!-- Nested structure -->
      <xsl:if test="item[@priority='high']">
        <urgent>
          <xsl:for-each select="item[@priority='high']">
            <xsl:choose>
              <xsl:when test="@status='pending'">
                <pending><xsl:value-of select="name"/></pending>
              </xsl:when>
              <xsl:otherwise>
                <other><xsl:value-of select="name"/></other>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:for-each>
        </urgent>
      </xsl:if>

      <!-- Local variable -->
      <xsl:variable name="total" select="sum(item/amount)"/>
      <total><xsl:value-of select="$total"/></total>

      <!-- Literal output with mixed content -->
      <footer>Generated by XSLT - <xsl:value-of select="count(item)"/> items</footer>
    </output>
  </xsl:template>

</xsl:stylesheet>
